[package]
name = "cyg"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
dialoguer = "0.10.0"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5.9"