use std::{fs, io::ErrorKind};

use crate::model;

use crate::utils;

pub fn init() {
    // Create .cyg directory if not exist
    // return error if exist
    match fs::create_dir(".cyg") {
        Ok(_) => (),
        Err(err) => {
            if err.kind() == ErrorKind::AlreadyExists {
                println!("error: Cyg already initialized in this repository!");
            } else {
                println!("error: {}", &err);
            }
            return;
        }
    }

    let app_name = utils::prompt::input(&"Your app name?");

    let config = model::Config {
        app: model::App { name: app_name },
        group: None,
    };

    let toml = toml::to_string(&config).unwrap();

    // Write to file with the comment on top of it
    let with_comment = format!("# This file is automatically generated by cyg.\n# It is not intended for manual editing.\n\n{}",
        toml
    );

    match fs::write(".cyg/cyg.toml", with_comment) {
        Ok(_) => (),
        Err(err) => println!("error: {}", err),
    }
}
